import type { IconName } from '@apptypes';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import type { ComponentProps } from 'react';

const ICON_MAP: Record<IconName, ComponentProps<typeof MaterialCommunityIcons>['name']> = {
  'dashboard': 'view-dashboard',
  'products': 'package-variant',
  'categories': 'tag-multiple',
  'inventory': 'clipboard-list-outline',
  'warehouses': 'warehouse',
  'branches': 'store-outline',
  'suppliers': 'truck-delivery-outline',
  'purchase-orders': 'clipboard-text-outline',
  'sales-orders': 'cart-outline',
  'pos': 'credit-card-chip-outline',
  'customers': 'account-group-outline',
  'employees': 'account-tie-outline',
  'reports': 'file-chart-outline',
  'analytics': 'chart-line',
  'notifications': 'bell-outline',
  'tasks': 'clipboard-check-outline',
  'profile': 'account-circle-outline',
  'settings': 'cog-outline',
  'help': 'help-circle-outline',
  'more': 'menu',
  'logout': 'logout',
  'menu': 'menu',
  'back': 'arrow-left',
  'search': 'magnify',
  'bell': 'bell-outline',
  'sun': 'white-balance-sunny',
  'moon': 'weather-night',
  'box': 'package-variant-closed',
  'tag': 'tag-outline',
  'warehouse': 'warehouse',
  'building': 'domain',
  'truck': 'truck-outline',
  'shopping-cart': 'cart-outline',
  'credit-card': 'credit-card-outline',
  'users': 'account-group-outline',
  'user': 'account-outline',
  'bar-chart': 'chart-bar',
  'trending-up': 'trending-up',
  'clipboard': 'clipboard-outline',
  'gear': 'cog-outline',
  'question': 'help-circle-outline',
  'chevron-right': 'chevron-right',
  'chevron-down': 'chevron-down',
  'plus': 'plus',
  'check': 'check',
  'x': 'close',
  'alert': 'alert-circle-outline',
  'wifi-off': 'wifi-off',
  'refresh': 'refresh',
  'package': 'package-variant-closed',
  'dollar': 'currency-usd',
  'receipt': 'receipt',
  'store': 'store-outline',
  'globe': 'web',
  'shield': 'shield-outline',
  'clock': 'clock-outline',
  'calendar': 'calendar-month-outline',
  'filter': 'filter-variant',
  'sort': 'sort-variant',
  'download': 'download',
  'upload': 'upload',
  'phone': 'phone-outline',
  'mail': 'email-outline',
  'map-pin': 'map-marker-outline',
  'camera': 'camera-outline',
  'qr': 'qrcode-scan',
  'barcode': 'barcode-scan',
  'eye': 'eye-outline',
  'eye-off': 'eye-off-outline',
  'lock': 'lock-outline',
  'unlock': 'lock-open-outline',
  'edit': 'pencil-outline',
  'trash': 'trash-can-outline',
  'archive': 'archive-outline',
  'folder': 'folder-outline',
  'file': 'file-outline',
  'image': 'image-outline',
  'star': 'star-outline',
  'heart': 'heart-outline',
  'info': 'information-outline',
  'external-link': 'open-in-new',
  'receiving': 'clipboard-arrow-down-outline',
  'scan': 'scan-helper',
  'map': 'map',
  'flag': 'flag-outline',
  'account': 'account-circle-outline',
  'email': 'email-outline',
  'history': 'history',
  'paperclip': 'paperclip',
  'file-export': 'file-export-outline',
  'file-pdf': 'file-pdf-box',
  'file-excel': 'file-excel-box',
  'file-csv': 'file-delimited-outline',
  'shield-check': 'shield-check-outline',
};

export function getIconName(name: IconName): ComponentProps<typeof MaterialCommunityIcons>['name'] {
  return ICON_MAP[name] ?? 'circle-outline';
}
